FROM node:9.3.0-alpine

ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin

RUN npm install -g create-react-app
RUN npm install -g serve

ADD yarn.lock /app/yarn.lock
ADD package.json /app/package.json

WORKDIR /app

RUN yarn install

ADD . /app

RUN yarn build

CMD ["serve", "-s", "build", "-p", "3000"]